databases:
  - name: dpg-cfirn59mbjsn9ecbpde0-a
    databaseName: dev_to
    user: dev_to_user

services:
  - type: web
    name: dev_to
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
